#![cfg(unix)]

use std::env;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[test]
fn build_target_script_defaults_to_the_rust_host_target() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("build-target");
    let script = fs::read_to_string(&script_path).expect("build-target script exists");
    let mode = fs::metadata(&script_path)
        .expect("build-target script is statable")
        .permissions()
        .mode();

    assert_ne!(mode & 0o111, 0, "build-target should be executable");
    assert!(script.contains("rustc -vV"));
    assert!(script.contains("host:"));
    assert!(script.contains("host_target="));
    assert!(script.contains(r#"target_list="${WORK_LEAF_BUILD_TARGETS:-$host_target}""#));
    assert!(script.contains("rustup target list --installed"));
    assert!(script.contains("rustup target add"));
    assert!(script.contains("cargo build --release --locked --bin work-leaf"));
    assert!(script.contains("Claude available on PATH when"));
    assert!(script.contains("Python SDK"));
    assert!(script.contains("TypeScript SDK"));
    assert!(script.contains("dist"));
    assert!(
        !script.contains("work-leaf-orchestrator"),
        "release packages should contain only the user-facing binary"
    );
}

#[test]
fn build_target_script_keeps_an_explicit_target_override_for_ci() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("build-target");
    let script = fs::read_to_string(&script_path).expect("build-target script exists");

    assert!(script.contains("WORK_LEAF_BUILD_TARGETS"));
    assert!(script.contains("for target in $target_list"));
}

#[test]
fn lockfile_matches_manifest_for_locked_release_builds() {
    let manifest = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml"))
        .expect("Cargo.toml is readable");
    let lockfile = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.lock"))
        .expect("Cargo.lock is readable");

    assert_eq!(
        package_version(&manifest, "work-leaf"),
        lockfile_package_version(&lockfile, "work-leaf"),
        "locked release builds require Cargo.lock to match Cargo.toml"
    );
}

#[test]
fn release_script_bumps_patch_version_refreshes_lock_and_tags_release() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("release");
    let script = fs::read_to_string(&script_path).expect("release script exists");
    let mode = fs::metadata(&script_path)
        .expect("release script is statable")
        .permissions()
        .mode();

    assert_ne!(mode & 0o111, 0, "release script should be executable");

    let temp_dir = unique_temp_dir("work-leaf-release-script");
    let fake_bin_dir = temp_dir.join("bin");
    fs::create_dir_all(&fake_bin_dir).expect("fake bin directory is created");
    let command_log = temp_dir.join("commands.log");

    write_executable(&temp_dir.join("release"), &script);
    write_executable(
        &temp_dir.join("build-target"),
        r#"#!/usr/bin/env bash
set -euo pipefail
printf 'build-target\n' >> "$WORK_LEAF_FAKE_COMMAND_LOG"
"#,
    );
    write_executable(
        &fake_bin_dir.join("cargo"),
        r#"#!/usr/bin/env bash
set -euo pipefail
printf 'cargo' >> "$WORK_LEAF_FAKE_COMMAND_LOG"
for arg in "$@"; do
  printf ' %s' "$arg" >> "$WORK_LEAF_FAKE_COMMAND_LOG"
done
printf '\n' >> "$WORK_LEAF_FAKE_COMMAND_LOG"

if [[ "${1:-}" == "check" ]]; then
  version="$(sed -n 's/^version = "\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)"$/\1/p' Cargo.toml | head -n 1)"
  VERSION="$version" perl -0pi -e 's/(\[\[package\]\]\nname = "work-leaf"\nversion = ")[^"]+(")/$1$ENV{VERSION}$2/' Cargo.lock
fi
"#,
    );
    write_executable(
        &fake_bin_dir.join("git"),
        r#"#!/usr/bin/env bash
set -euo pipefail
printf 'git' >> "$WORK_LEAF_FAKE_COMMAND_LOG"
for arg in "$@"; do
  printf ' %s' "$arg" >> "$WORK_LEAF_FAKE_COMMAND_LOG"
done
printf '\n' >> "$WORK_LEAF_FAKE_COMMAND_LOG"

if [[ "${1:-}" == "status" && "${2:-}" == "--porcelain" ]]; then
  exit 0
fi
if [[ "${1:-}" == "tag" && "${2:-}" == "--list" ]]; then
  exit 0
fi
"#,
    );
    fs::write(
        temp_dir.join("Cargo.toml"),
        "[package]\nname = \"work-leaf\"\nversion = \"1.2.3\"\nedition = \"2024\"\n",
    )
    .expect("Cargo.toml fixture is written");
    fs::write(
        temp_dir.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"work-leaf\"\nversion = \"1.2.3\"\n",
    )
    .expect("Cargo.lock fixture is written");

    let original_path = env::var_os("PATH").expect("PATH is set for release script test");
    let mut paths = vec![fake_bin_dir];
    paths.extend(env::split_paths(&original_path));
    let path = env::join_paths(paths).expect("fake command PATH can be joined");

    let output = Command::new("bash")
        .arg(temp_dir.join("release"))
        .env("PATH", path)
        .env("WORK_LEAF_FAKE_COMMAND_LOG", &command_log)
        .output()
        .expect("release script runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "release script should succeed with fake commands\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );

    let manifest = fs::read_to_string(temp_dir.join("Cargo.toml")).unwrap();
    let lockfile = fs::read_to_string(temp_dir.join("Cargo.lock")).unwrap();
    assert_eq!(package_version(&manifest, "work-leaf"), "1.2.4");
    assert_eq!(lockfile_package_version(&lockfile, "work-leaf"), "1.2.4");

    let log = fs::read_to_string(&command_log).expect("fake command log is readable");
    assert_ordered(
        &log,
        &[
            "git status --porcelain",
            "git tag --list v1.2.4",
            "cargo check",
            "cargo check --locked",
            "cargo fmt",
            "cargo clippy --all-targets --all-features -- -D warnings",
            "cargo test --all-targets --all-features",
            "build-target",
            "git add Cargo.toml Cargo.lock",
            "git commit -m UPDATE bump release version to v1.2.4 so locked release builds use matching metadata",
            "git tag v1.2.4",
        ],
    );

    let _ = fs::remove_dir_all(temp_dir);
}

#[test]
fn build_target_script_installs_missing_rustup_target_before_build() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("build-target");
    let temp_dir = unique_temp_dir("work-leaf-build-target");
    let fake_bin_dir = temp_dir.join("bin");
    fs::create_dir_all(&fake_bin_dir).expect("fake bin directory is created");
    let command_log = temp_dir.join("commands.log");
    let target = "work-leaf-test-target";

    write_executable(
        &fake_bin_dir.join("rustc"),
        r#"#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "-vV" ]]; then
  printf 'rustc 1.0.0\n'
  printf 'host: x86_64-unknown-linux-gnu\n'
  exit 0
fi
echo "unexpected rustc args: $*" >&2
exit 1
"#,
    );
    write_executable(
        &fake_bin_dir.join("rustup"),
        r#"#!/usr/bin/env bash
set -euo pipefail
printf 'rustup' >> "$WORK_LEAF_FAKE_COMMAND_LOG"
for arg in "$@"; do
  printf ' %s' "$arg" >> "$WORK_LEAF_FAKE_COMMAND_LOG"
done
printf '\n' >> "$WORK_LEAF_FAKE_COMMAND_LOG"

if [[ "${1:-}" == "target" && "${2:-}" == "list" && "${3:-}" == "--installed" ]]; then
  printf '%s\n' "${WORK_LEAF_FAKE_INSTALLED_TARGETS:-}"
  exit 0
fi

if [[ "${1:-}" == "target" && "${2:-}" == "add" && -n "${3:-}" ]]; then
  exit 0
fi

echo "unexpected rustup args: $*" >&2
exit 1
"#,
    );
    write_executable(
        &fake_bin_dir.join("cargo"),
        r#"#!/usr/bin/env bash
set -euo pipefail
printf 'cargo' >> "$WORK_LEAF_FAKE_COMMAND_LOG"
for arg in "$@"; do
  printf ' %s' "$arg" >> "$WORK_LEAF_FAKE_COMMAND_LOG"
done
printf '\n' >> "$WORK_LEAF_FAKE_COMMAND_LOG"

target=""
previous=""
for arg in "$@"; do
  if [[ "$previous" == "--target" ]]; then
    target="$arg"
  fi
  previous="$arg"
done

if [[ -z "$target" ]]; then
  echo "cargo build did not receive --target" >&2
  exit 1
fi

binary_name="work-leaf"
case "$target" in
  *-pc-windows-*)
    binary_name="work-leaf.exe"
    ;;
esac

mkdir -p "target/$target/release"
printf 'fake binary\n' > "target/$target/release/$binary_name"
"#,
    );

    let original_path = env::var_os("PATH").expect("PATH is set for build-target test");
    let mut paths = vec![fake_bin_dir.clone()];
    paths.extend(env::split_paths(&original_path));
    let path = env::join_paths(paths).expect("fake command PATH can be joined");

    let output = Command::new("bash")
        .arg(&script_path)
        .env("PATH", path)
        .env("WORK_LEAF_BUILD_TARGETS", target)
        .env("WORK_LEAF_DIST_DIR", temp_dir.join("dist"))
        .env("WORK_LEAF_FAKE_COMMAND_LOG", &command_log)
        .env(
            "WORK_LEAF_FAKE_INSTALLED_TARGETS",
            "x86_64-unknown-linux-gnu",
        )
        .output()
        .expect("build-target script runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "build-target should succeed with fake commands\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        temp_dir
            .join("dist")
            .join(format!("work-leaf-{target}"))
            .join("work-leaf")
            .exists(),
        "build-target should package the fake built binary"
    );

    let log = fs::read_to_string(&command_log).expect("fake command log is readable");
    let rustup_list = log
        .find("rustup target list --installed")
        .expect("script checks installed Rust targets");
    let rustup_add = log
        .find(&format!("rustup target add {target}"))
        .expect("script installs the missing Rust target");
    let cargo_build = log
        .find(&format!(
            "cargo build --release --locked --bin work-leaf --target {target}"
        ))
        .expect("script builds after preparing the target");

    assert!(
        rustup_list < rustup_add && rustup_add < cargo_build,
        "expected rustup target add before cargo build, got:\n{log}"
    );

    let repo_target_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("target")
        .join(target);
    let _ = fs::remove_dir_all(repo_target_dir);
    let _ = fs::remove_dir_all(temp_dir);
}

#[test]
fn github_release_workflow_builds_each_binary_on_its_native_runner() {
    let workflow_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(".github")
        .join("workflows")
        .join("release-binaries.yml");
    let workflow = fs::read_to_string(&workflow_path).expect("release workflow exists");

    assert!(workflow.contains("ubuntu-24.04"));
    assert!(workflow.contains("ubuntu-24.04-arm"));
    assert!(workflow.contains("macos-15-intel"));
    assert!(workflow.contains("macos-15"));
    assert!(workflow.contains("windows-2025"));
    assert!(workflow.contains("windows-11-arm"));
    assert!(workflow.contains("x86_64-unknown-linux-gnu"));
    assert!(workflow.contains("aarch64-unknown-linux-gnu"));
    assert!(workflow.contains("x86_64-apple-darwin"));
    assert!(workflow.contains("aarch64-apple-darwin"));
    assert!(workflow.contains("x86_64-pc-windows-msvc"));
    assert!(workflow.contains("aarch64-pc-windows-msvc"));
    assert!(workflow.contains("rustup toolchain install stable --profile minimal"));
    assert!(workflow.contains("WORK_LEAF_BUILD_TARGETS"));
    assert!(workflow.contains("./build-target"));
    assert!(workflow.contains("actions/upload-artifact"));
    assert!(
        workflow.contains("build-essential"),
        "linux runners should install the native compiler/linker package explicitly"
    );
}

#[test]
fn github_release_workflow_builds_the_requested_tag_ref() {
    let workflow_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(".github")
        .join("workflows")
        .join("release-binaries.yml");
    let workflow = fs::read_to_string(&workflow_path).expect("release workflow exists");

    assert!(
        workflow.contains(
            "ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}"
        ),
        "release builds must checkout the requested tag/ref before running build-target so --locked builds use the tag's Cargo.lock"
    );
    assert!(
        workflow.contains("built_commit=\"$(git rev-parse HEAD)\""),
        "release tag verification must compare against the checked-out ref, not the workflow dispatch branch SHA"
    );
}

#[test]
fn github_release_workflow_publishes_sha256_checksums_for_release_archives() {
    let workflow_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(".github")
        .join("workflows")
        .join("release-binaries.yml");
    let workflow = fs::read_to_string(&workflow_path).expect("release workflow exists");

    assert!(workflow.contains("sha256sum"));
    assert!(workflow.contains("*.sha256"));
    assert!(workflow.contains("release-assets/*.sha256"));
}

#[test]
fn install_script_installs_requested_release_after_checksum_verification() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("install.sh");
    let script_mode = fs::metadata(&script_path)
        .expect("install.sh exists")
        .permissions()
        .mode();
    assert_ne!(script_mode & 0o111, 0, "install.sh should be executable");

    let temp_dir = unique_temp_dir("work-leaf-install");
    let release_dir = temp_dir.join("release");
    let install_dir = temp_dir.join("bin");
    fs::create_dir_all(&release_dir).expect("release dir is created");
    fs::create_dir_all(&install_dir).expect("install dir is created");

    write_release_archive(&release_dir, "x86_64-unknown-linux-gnu", "1.2.3", true);

    let output = Command::new("bash")
        .arg(&script_path)
        .env("WORK_LEAF_INSTALL_BASE_URL", file_url(&release_dir))
        .env("WORK_LEAF_INSTALL_DIR", &install_dir)
        .env("WORK_LEAF_INSTALL_TARGET", "x86_64-unknown-linux-gnu")
        .env("WORK_LEAF_INSTALL_VERSION", "v1.2.3")
        .output()
        .expect("install.sh runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "install.sh should succeed\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(stdout.contains("Installed work-leaf v1.2.3"));

    let installed = install_dir.join("work-leaf");
    assert!(installed.exists(), "install.sh should install work-leaf");
    assert_ne!(
        fs::metadata(&installed).unwrap().permissions().mode() & 0o111,
        0,
        "installed work-leaf should be executable"
    );

    let version_output = Command::new(&installed)
        .arg("--version")
        .output()
        .expect("installed fake binary runs");
    assert!(version_output.status.success());
    assert_eq!(
        String::from_utf8_lossy(&version_output.stdout),
        "work-leaf 1.2.3\n"
    );

    let _ = fs::remove_dir_all(temp_dir);
}

#[test]
fn install_script_skips_matching_installed_version_without_downloading() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("install.sh");
    let temp_dir = unique_temp_dir("work-leaf-install-skip");
    let install_dir = temp_dir.join("bin");
    fs::create_dir_all(&install_dir).expect("install dir is created");

    write_executable(
        &install_dir.join("work-leaf"),
        r#"#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "--version" ]]; then
  printf 'work-leaf 1.2.3\n'
  exit 0
fi
exit 1
"#,
    );

    let output = Command::new("bash")
        .arg(&script_path)
        .env(
            "WORK_LEAF_INSTALL_BASE_URL",
            file_url(&temp_dir.join("missing")),
        )
        .env("WORK_LEAF_INSTALL_DIR", &install_dir)
        .env("WORK_LEAF_INSTALL_TARGET", "x86_64-unknown-linux-gnu")
        .env("WORK_LEAF_INSTALL_VERSION", "v1.2.3")
        .output()
        .expect("install.sh runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "install.sh should skip before downloading\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(stdout.contains("work-leaf v1.2.3 is already installed"));

    let _ = fs::remove_dir_all(temp_dir);
}

#[test]
fn install_script_rejects_release_archive_when_checksum_mismatches() {
    let script_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("install.sh");
    let temp_dir = unique_temp_dir("work-leaf-install-checksum");
    let release_dir = temp_dir.join("release");
    let install_dir = temp_dir.join("bin");
    fs::create_dir_all(&release_dir).expect("release dir is created");
    fs::create_dir_all(&install_dir).expect("install dir is created");

    write_release_archive(&release_dir, "x86_64-unknown-linux-gnu", "1.2.3", false);

    let output = Command::new("bash")
        .arg(&script_path)
        .env("WORK_LEAF_INSTALL_BASE_URL", file_url(&release_dir))
        .env("WORK_LEAF_INSTALL_DIR", &install_dir)
        .env("WORK_LEAF_INSTALL_TARGET", "x86_64-unknown-linux-gnu")
        .env("WORK_LEAF_INSTALL_VERSION", "v1.2.3")
        .output()
        .expect("install.sh runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        !output.status.success(),
        "install.sh should fail on checksum mismatch\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        stderr.contains("checksum") || stdout.contains("checksum"),
        "checksum failures should explain the verification problem\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        !install_dir.join("work-leaf").exists(),
        "checksum failure must not install work-leaf"
    );

    let _ = fs::remove_dir_all(temp_dir);
}

fn unique_temp_dir(prefix: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time is after the Unix epoch")
        .as_nanos();
    let dir = env::temp_dir().join(format!("{prefix}-{}-{nanos}", std::process::id()));
    fs::create_dir_all(&dir).expect("temporary directory is created");
    dir
}

fn write_executable(path: &Path, contents: &str) {
    fs::write(path, contents).expect("fake executable is written");
    let mut permissions = fs::metadata(path)
        .expect("fake executable metadata is readable")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions).expect("fake executable is executable");
}

fn write_release_archive(release_dir: &Path, target: &str, version: &str, valid_checksum: bool) {
    let package_dir = release_dir.join(format!("work-leaf-{target}"));
    fs::create_dir_all(&package_dir).expect("package dir is created");
    write_executable(
        &package_dir.join("work-leaf"),
        &format!(
            r#"#!/usr/bin/env bash
set -euo pipefail
if [[ "${{1:-}}" == "--version" ]]; then
  printf 'work-leaf {version}\n'
  exit 0
fi
printf 'fake work-leaf {version}\n'
"#
        ),
    );

    let archive_name = format!("work-leaf-{target}.tar.gz");
    let archive_path = release_dir.join(&archive_name);
    let tar_output = Command::new("tar")
        .arg("-czf")
        .arg(&archive_path)
        .arg("-C")
        .arg(release_dir)
        .arg(format!("work-leaf-{target}"))
        .output()
        .expect("tar creates test release archive");
    assert!(
        tar_output.status.success(),
        "tar should create release archive\nstderr:\n{}",
        String::from_utf8_lossy(&tar_output.stderr)
    );

    let checksum = if valid_checksum {
        sha256_hex(&archive_path)
    } else {
        "0000000000000000000000000000000000000000000000000000000000000000".to_string()
    };
    fs::write(
        release_dir.join(format!("{archive_name}.sha256")),
        format!("{checksum}  {archive_name}\n"),
    )
    .expect("checksum file is written");
}

fn sha256_hex(path: &Path) -> String {
    let output = match Command::new("sha256sum").arg(path).output() {
        Ok(output) => output,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Command::new("shasum")
            .arg("-a")
            .arg("256")
            .arg(path)
            .output()
            .expect("sha256sum or shasum is available for checksum tests"),
        Err(error) => panic!("sha256sum failed to start for checksum tests: {error}"),
    };
    assert!(
        output.status.success(),
        "checksum tool should hash archive\nstderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout)
        .split_whitespace()
        .next()
        .expect("sha256sum prints a digest")
        .to_string()
}

fn file_url(path: &Path) -> String {
    format!("file://{}", path.display())
}

fn package_version(contents: &str, package_name: &str) -> String {
    let mut in_package = false;
    let mut name_matches = false;
    let mut version = None;

    for line in contents.lines().map(str::trim) {
        if line.starts_with('[') {
            if in_package {
                break;
            }
            in_package = line == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(name) = quoted_value(line, "name") {
            name_matches = name == package_name;
        }
        if let Some(value) = quoted_value(line, "version") {
            version = Some(value.to_string());
        }
    }

    assert!(
        name_matches,
        "Cargo.toml [package] should be {package_name}"
    );
    version.expect("Cargo.toml [package] should have a version")
}

fn lockfile_package_version(contents: &str, package_name: &str) -> String {
    let mut in_package = false;
    let mut name_matches = false;
    let mut version = None;

    for line in contents.lines().map(str::trim) {
        if line == "[[package]]" {
            if name_matches {
                break;
            }
            in_package = true;
            name_matches = false;
            version = None;
            continue;
        }
        if line.starts_with('[') {
            in_package = false;
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(name) = quoted_value(line, "name") {
            name_matches = name == package_name;
        }
        if let Some(value) = quoted_value(line, "version") {
            version = Some(value.to_string());
        }
    }

    assert!(
        name_matches,
        "Cargo.lock should contain a package entry for {package_name}"
    );
    version.expect("Cargo.lock package entry should have a version")
}

fn quoted_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim_start();
    let rest = rest.strip_prefix('"')?;
    rest.split('"').next()
}

fn assert_ordered(haystack: &str, needles: &[&str]) {
    let mut cursor = 0;
    for needle in needles {
        let Some(relative_index) = haystack[cursor..].find(needle) else {
            panic!("expected `{needle}` after byte {cursor} in:\n{haystack}");
        };
        cursor += relative_index + needle.len();
    }
}
